In [2]:
import pandas as pd
import plotly.express as px

# Loading the dataset
car_sales_df=pd.read_csv("/home/pragyanp/Desktop/Pandas_NLP_DL/Datasets/car_sales_usa_data 1.csv",parse_dates=["Sale Date"])
car_sales_df

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State
0,2004,Ford,Explorer,Limited,SUV,Automatic,1fmzu65k54ua59709,171116,Barnett Finance Company,2500,1700,2015-02-17,Georgia
1,2013,Chevrolet,Impala,LS Fleet,sedan,Automatic,2g1wf5e3xd1160771,57634,The Hertz Corporation,8925,8900,2015-06-16,California
2,2014,Dodge,Grand Caravan,SXT,Minivan,Automatic,2c4rdgcg2er173190,37928,Avis Corporation,16200,16200,2015-02-12,South Carolina
3,2007,Ford,F-150,XLT,supercab,Automatic,1ftpx14557fa02257,108246,Tdaf Remarketing,10300,11000,2015-06-16,Florida
4,2011,Hyundai,Elantra,GLS PZEV,Sedan,Automatic,5npdh4aexbh018071,69185,Wholesale Inc # 2,9575,10300,2015-01-21,Tennessee
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2013,Nissan,Altima,2.5,Sedan,Automatic,1n4al3ap5dn468314,32702,Nissan-Infiniti Lt,13800,13000,2015-02-26,Illinois
49996,2005,Mercedes-Benz,E-Class,E320,Sedan,Automatic,wdbuf65j95a624447,123165,Westlake Financial Services,6075,4100,2015-01-08,Florida
49997,2013,Dodge,Dart,SXT,Sedan,Automatic,1c3cdfba9dd143722,47130,Wells Fargo Dealer Services,11400,11000,2015-03-04,Texas
49998,2008,Toyota,RAV4,Limited,SUV,Automatic,jtmzd31vx85115663,102712,Infinity Auto Sales Llc,9525,8600,2015-03-05,Virginia
49999,2013,Chevrolet,Camaro,SS,Convertible,Automatic,2g1fk3dj8d9138852,53105,Tdaf Remarketing,21400,23400,2015-02-17,Florida

In [3]:
# Function to explore the dataset
def explore_data(car_sales_df:pd.DataFrame)->None:
    print(f"{car_sales_df.sample(3)}")
    print(f"Info of the dataset : {car_sales_df.info()}")
    print(f"Description of the dataset : {car_sales_df.describe()}")
    print(f"Index of the dataset : {car_sales_df.index}")
    print(f"All the columns of the dataset : {car_sales_df.columns}")

# Function to conver the column into the categorical form
def convert_categorical(car_sales_df:pd.DataFrame , columns:list[str])->pd.DataFrame:
    for col in columns:
        car_sales_df[col]=pd.Categorical(car_sales_df[col])

    return car_sales_df

In [4]:
explore_data(car_sales_df)

car_sales_df=convert_categorical(car_sales_df,["Transmission","Body","Make"])

       Year   Make     Model    Trim   Body Transmission  \
47411  2010    BMW  3 Series    328i  Sedan    Automatic
32184  2004  Honda     Civic  Hybrid  Sedan    Automatic
35913  2011  Honda    Accord    LX-P  Sedan    Automatic

      Vehicle Identification Number  Odometer  \
47411             wbaph7g51anm49321     67685
32184             jhmes96614s005040    103785
35913             1hgcp2f42ba150351     67721

                                             Seller  Market Price  \
47411        Financial Services Remarketing (Repos)         13500
32184                         Nalley Nissan Decatur          3000
35913  Regional Acceptance Corporation / Greenville          9775

       Selling Price  Sale Date    State
47411          12500 2015-05-22   Nevada
32184           3000 2015-01-27  Georgia
35913           3600 2015-02-23  Florida
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Year                           50000 non-null  int64
 1   Make                           50000 non-null  object
 2   Model                          50000 non-null  object
 3   Trim                           50000 non-null  object
 4   Body                           49999 non-null  object
 5   Transmission                   50000 non-null  object
 6   Vehicle Identification Number  50000 non-null  object
 7   Odometer                       50000 non-null  int64
 8   Seller                         50000 non-null  object
 9   Market Price                   50000 non-null  int64
 10  Selling Price                  50000 non-null  int64
 11  Sale Date                      50000 non-null  datetime64[ns]
 12  State                          50000 non-null  object
dtypes: datetime64[ns](1), int64(4), object(8)
memory usage: 5.0+ MB
Info of the dataset : None
Description of the dataset :                Year       Odometer   Market Price  Selling Price  \
count  50000.000000   50000.000000   50000.000000   50000.000000
mean    2010.222180   66914.303020   13756.794020   13610.046100
min     1990.000000       1.000000      25.000000     100.000000
25%     2008.000000   28022.000000    7375.000000    7100.000000
50%     2012.000000   50729.000000   12300.000000   12200.000000
75%     2013.000000   97067.500000   18162.500000   18100.000000
max     2015.000000  999999.000000  146000.000000  150000.000000
std        3.830409   52725.342267    9429.611407    9486.603904

                        Sale Date
count                       50000
mean   2015-03-07 11:26:09.600000
min           2014-01-01 00:00:00
25%           2015-01-21 00:00:00
50%           2015-02-17 00:00:00
75%           2015-05-22 00:00:00
max           2015-07-09 00:00:00
std                           NaN
Index of the dataset : RangeIndex(start=0, stop=50000, step=1)
All the columns of the dataset : Index(['Year', 'Make', 'Model', 'Trim', 'Body', 'Transmission',
       'Vehicle Identification Number', 'Odometer', 'Seller', 'Market Price',
       'Selling Price', 'Sale Date', 'State'],
      dtype='object')

### How many records are there per model Year?

In [36]:
records_per_year=car_sales_df.groupby([car_sales_df["Sale Date"].dt.year]).size()
# records_per_year.index=[(idx[0]+"_"+str(idx[1])) for idx in records_per_year.index]
records_per_year_df=pd.DataFrame(records_per_year)
# type(records_per_year_df)
display(records_per_year_df)
print(records_per_year_df.columns)

               0
Sale Date
2014        3928
2015       46072

RangeIndex(start=0, stop=1, step=1)

In [41]:
px.bar(data_frame=records_per_year_df,x=records_per_year_df.index , y=records_per_year_df[0])

###  What is the distribution of vehicle age at sale (Age = Sale Year − Model Year)? Provide basic statistics (count, mean, median, std, min, 25 %, 50 %, 75 %, max).

In [7]:
new_df=car_sales_df
new_df["Age"]=car_sales_df["Sale Date"].dt.year - car_sales_df["Year"]
new_df["Age"].describe()

count    50000.000000
mean         4.699260
std          3.828204
min         -1.000000
25%          2.000000
50%          3.000000
75%          7.000000
max         25.000000
Name: Age, dtype: float64

### Which Body styles are most common? List the top‑5 body styles with their frequencies

In [8]:
new_data=car_sales_df["Body"].value_counts().head(5)
new_data

Body
Sedan        18515
SUV          10466
sedan         3972
suv           2219
Hatchback     2054
Name: count, dtype: int64

### What are the minimum, maximum, and average odometer readings across the whole dataset?

In [9]:
stats_data=car_sales_df[["Odometer"]].agg(["min","max","mean"])
stats_data.T

          min       max         mean
Odometer  1.0  999999.0  66914.30302

### How many unique sellers exist in each State?

In [10]:
unique_sellers=car_sales_df.groupby("State")[["Seller"]].nunique()
unique_sellers

                Seller
State
Arizona            159
California         800
Colorado           121
Florida            824
Georgia            410
Hawaii              44
Illinois           174
Indiana             84
Louisiana           38
Maryland           145
Massachusetts      106
Michigan           132
Minnesota          169
Mississippi         48
Missouri           266
Nebraska           101
Nevada             255
New Jersey         299
New Mexico          11
New York            89
North Carolina     317
Ohio               222
Oklahoma             4
Oregon              44
Pennsylvania       489
Puerto Rico         34
South Carolina      92
Tennessee          195
Texas              515
Utah                48
Virginia           190
Washington         134
Wisconsin          171

### Show all rows where Selling Price > Market Price.

In [11]:
car_sales_df[car_sales_df["Selling Price"] > car_sales_df["Market Price"]]

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
3,2007,Ford,F-150,XLT,supercab,Automatic,1ftpx14557fa02257,108246,Tdaf Remarketing,10300,11000,2015-06-16,Florida,8
4,2011,Hyundai,Elantra,GLS PZEV,Sedan,Automatic,5npdh4aexbh018071,69185,Wholesale Inc # 2,9575,10300,2015-01-21,Tennessee,4
5,2012,Nissan,Leaf,SL,Hatchback,Automatic,jn1az0cp2ct018461,23801,Nissan Motor Acceptance Corporation,10600,11100,2015-02-25,California,3
6,2010,Dodge,Avenger,SXT,Sedan,Automatic,1b3cc4fb2an189535,110704,Exeter Finance Corp,5100,5600,2015-02-10,Tennessee,5
9,2012,Honda,Accord,LX,Sedan,Automatic,1hgcp2f36ca167629,35478,Ahfc/Honda Lease Trust/Hvt Inc. Eot,11850,12300,2015-05-22,Nevada,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49981,2014,Chevrolet,Cruze,1LT,Sedan,Automatic,1g1pc5sbxe7180760,38916,Avis Corporation,11600,12500,2015-03-03,Texas,1
49987,2012,Infiniti,M,M37x,sedan,Automatic,jn1by1ar8cm393945,52454,Nissan Infiniti Lt,22000,22400,2015-06-18,Illinois,3
49991,2013,Lexus,GS 350,Base,sedan,Automatic,jthbe1bl2d5014108,26897,High Bid Trading Co Inc,30500,31500,2015-06-18,California,2
49992,2012,Lexus,ES 350,Base,Sedan,Automatic,jthbk1egxc2492283,30255,Lexus Financial Services,21900,24750,2015-02-04,California,3
49999,2013,Chevrolet,Camaro,SS,Convertible,Automatic,2g1fk3dj8d9138852,53105,Tdaf Remarketing,21400,23400,2015-02-17,Florida,2

### Retrieve automatic‑transmission vehicles in California with Odometer < 30 000 miles.

In [12]:
car_sales_df[(car_sales_df["Transmission"]=="Automatic") & (car_sales_df["State"] == "California") & (car_sales_df["Odometer"] < 30000)]

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
5,2012,Nissan,Leaf,SL,Hatchback,Automatic,jn1az0cp2ct018461,23801,Nissan Motor Acceptance Corporation,10600,11100,2015-02-25,California,3
33,2011,BMW,3 Series,328i,Sedan,Automatic,wbaph5c54bf093310,29639,Financial Services Remarketing (Lease),19050,17900,2015-02-12,California,4
35,2013,Honda,Civic,LX,Sedan,Automatic,19xfb2f53de240787,14379,Ahfc/Honda Lease Trust/Hvt Inc.,13650,14900,2015-01-29,California,2
44,2015,Nissan,Altima,2.5 S,Sedan,Automatic,1n4al3ap2fn315814,18181,Enterprise Veh Exchange/Rental,16050,16600,2015-02-19,California,0
66,2014,Jeep,Compass,Sport,SUV,Automatic,1c4njcba5ed817877,19984,Hertz Corporation/Gdp,14050,13900,2015-06-03,California,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49943,2014,Dodge,Grand Caravan,SXT,Minivan,Automatic,2c4rdgcg6er430304,13482,Enterprise Vehicle Exchange / Tra / Rental / T...,17150,12300,2015-01-22,California,1
49953,2014,Ford,Focus,SE,Sedan,Automatic,1fadp3f25el242155,17734,Ford Motor Credit Company,12600,12600,2015-01-29,California,1
49968,2010,Jeep,Wrangler,Sport,SUV,Automatic,1j4aa2d18al146575,15745,Aaero Sweet Company,19100,22000,2015-02-26,California,5
49984,2014,Mercedes-Benz,CLA-Class,CLA250,Sedan,Automatic,wddsj4eb2en035064,6017,Mercedes-Benz Usa,29700,24750,2014-12-18,California,0
49991,2013,Lexus,GS 350,Base,sedan,Automatic,jthbe1bl2d5014108,26897,High Bid Trading Co Inc,30500,31500,2015-06-18,California,2

### For each Make, keep the record with the most recent Sale Date.

In [13]:
grouped_make=car_sales_df.groupby("Make")[["Sale Date"]].idxmax()
grouped_make.reset_index()
car_sales_df.loc[grouped_make['Sale Date']]
# grouped_make['Sale Date']
# print(grouped_make.columns)
# print(grouped_make.index)

/tmp/ipykernel_47322/3073332397.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
34661,2005,Acura,RSX,Base,hatchback,Automatic,jh4dc54825s004888,143669,Ed Napleton Acura,3525,1900,2015-07-08,Wisconsin,10
5806,2008,Aston Martin,V8 Vantage,N400 Roadster,convertible,Automatic,scfbf04b08gd08294,13479,Performance Auto Sales Llc,55200,57000,2015-06-17,Florida,7
19405,2010,Audi,A4,2.0T Premium quattro,Sedan,Manual,waudfafl8an047964,80318,Rob Lambdin'S University Dodge,12400,12200,2015-07-03,Florida,5
4891,2012,BMW,3 Series,328i,Sedan,Automatic,wba3a5c54cf347733,35587,Lauderdale Imports Ltd Bmw Pembrok Pines,21600,23200,2015-07-07,Florida,3
45450,2005,Bentley,Continental GT,Base,Coupe,Automatic,scbcr63w15c025701,42409,Payless Auto Sales Inc,48600,54000,2015-07-02,California,10
17292,2011,Buick,LaCrosse,CXL,Sedan,Automatic,1g4gc5edxbf133777,83050,Gm Financial,11950,13003,2015-07-03,Texas,4
36145,2013,Cadillac,XTS,Platinum,sedan,Automatic,2g61u5s34d9198920,33603,Wells Fargo Dealer Services,31300,31800,2015-07-02,Texas,2
17943,2013,Chevrolet,Impala,LTZ,Sedan,Automatic,2g1wc5e39d1214070,60025,The Hertz Corporation,10100,10300,2015-07-08,California,2
2031,2013,Chrysler,200,LX,Sedan,Automatic,1c3ccbab2dn734510,45108,Enterprise Veh Exchange/Rental,9500,10900,2015-07-09,California,2
4576,2014,Dodge,Challenger,SXT,Coupe,Automatic,2c3cdyagxeh233855,26802,Enterprise Veh Exchange/Rental,18200,18900,2015-07-08,California,1
21507,2013,FIAT,500,Sport,Hatchback,Automatic,3c3cffbr0dt618555,47634,The Hertz Corporation,8475,8900,2015-06-18,Illinois,2
49965,2012,Fisker,Karma,Eco-Sport,Sedan,Automatic,yh4k14aa4ca000463,18593,Innovative Auto Llc,48200,46500,2015-02-12,Georgia,3
2783,2015,Ford,Fusion,SE,Sedan,Automatic,3fa6p0h71fr189618,10,Ford Motor Credit Company,33900,42100,2015-07-09,Tennessee,0
36634,2014,GMC,Savana Cargo,2500,Van,Automatic,1gtw7fca7e1904930,13849,U-Haul,18950,19800,2015-06-24,Tennessee,1
18209,1995,Geo,Prizm,Base,Sedan,Automatic,1y1sk5266sz002895,162909,Purple Heart Services Inc,500,550,2015-05-28,New Jersey,20
18955,2006,HUMMER,H3,Base,suv,Automatic,5gtdn136368101660,91398,Multi Auto Trading Inc,11400,10000,2015-07-09,Michigan,9
9397,2010,Honda,Civic,LX,coupe,Automatic,2hgfg1b69ah503277,70554,M & M Cars Trucks Vans Inc,7125,7600,2015-07-07,California,5
13801,2015,Hyundai,Genesis,3.8,Sedan,Automatic,kmhgn4je0fu039752,3866,Hyundai Motor Finance,35300,34000,2015-07-03,Florida,0
31701,2012,Infiniti,G Coupe,G37x,G Coupe,Automatic,jn1cv6el0cm470372,54680,Nissan Infiniti Lt,19400,17200,2015-07-09,Tennessee,3
20521,1999,Isuzu,Rodeo,S,suv,Automatic,4s2ck58w3x4355717,122039,Park Cities Volkswagen,925,1100,2015-06-11,Texas,16
928,2011,Jaguar,XK,Base,coupe,Automatic,sajwa4fb6blb40731,26922,Luxury Motor Car Company,37700,39500,2015-06-18,Ohio,4
1561,2008,Jeep,Patriot,Sport,suv,Automatic,1j8ff28w48d784872,85290,Select Lane,6450,7300,2015-07-09,Minnesota,7
21115,2012,Kia,Optima,LX,Sedan,Automatic,5xxgm4a70cg062555,75262,Kia Motors Finance,9650,8500,2015-07-08,Minnesota,3
31995,2007,Lamborghini,Gallardo,Spyder,Convertible,Automatic,zhwgu22t97la05738,18624,Richard J Bartlett Jr Enterprises,111000,110000,2015-05-21,California,8
4373,2012,Land Rover,Range Rover Evoque,Pure,suv,Automatic,salvr2bg3ch685496,21570,Okemos Auto Collection,34600,32000,2015-06-18,Michigan,3
35884,2008,Lexus,LS 460,Base,sedan,Automatic,jthbl46f185052818,110153,Plaza Motor Company,17350,15000,2015-07-07,Missouri,7
17457,2013,Lincoln,MKX,Base,SUV,Automatic,2lmdj8jk8dbl18076,20759,Ford Motor Credit Company Llc,28500,27300,2015-07-08,Michigan,2
17172,2012,MINI,Cooper,Base,hatchback,Manual,wmwsu3c53ct186235,31904,Bmw Mini Financial Services,11250,10600,2015-06-19,Nevada,3
8067,2006,Maserati,Quattroporte,Base,sedan,Automatic,zamce39a260023277,62538,E Motor Cars,18500,18000,2015-06-18,California,9
49037,2008,Mazda,B-Series Truck,B4000,Cab Plus 4,Manual,4f4zr47e88pm00663,38364,Automobiles Paille Inc,11300,12500,2015-06-30,Michigan,7
28531,2009,Mercedes-Benz,C-Class,C350 Sport,Sedan,Automatic,wddgf56x19f215580,96147,Meridian Remarketing,12450,12700,2015-07-08,Texas,6
2090,2001,Mercury,Sable,LS Premium,sedan,Automatic,1mefm55s11a648656,125741,Brandon Mitsubishi,675,500,2015-06-18,Florida,14
49952,2010,Mitsubishi,Outlander,ES,SUV,Automatic,ja4as2aw4az014522,69079,Reliable Financial Services Inc,6550,8300,2015-07-02,Puerto Rico,5
47112,2014,Nissan,Maxima,3.5 S,Sedan,Automatic,1n4aa5ap1ec457602,32231,Avis Corporation,15500,16800,2015-07-09,Texas,1
19937,2002,Oldsmobile,Alero,GX,sedan,Automatic,1g3nk52f12c223423,108862,Darcars Toyota Of Frederick,950,550,2015-06-16,Maryland,13
5510,1998,Plymouth,Neon,Style,Sedan,Automatic,3p3es47c6wt258638,103110,Dt Credit Corporation,700,400,2015-05-28,California,17
35565,2009,Pontiac,Torrent,Base,SUV,Automatic,2ckdl33f096201887,49450,Tdaf Remarketing,9475,10500,2015-06-30,Florida,6
9828,2009,Porsche,Cayenne,GTS,suv,Automatic,wp1ad29p49la60409,65234,Kapitolia Auto Llc,30200,30250,2015-06-19,Nevada,6
5886,2013,Ram,2500,Tradesman,Crew Cab,Automatic,3c6ur5hl6dg580964,92961,Enterprise Fleet Management Exchange,22500,23500,2015-07-02,Texas,2
14989,2011,Rolls-Royce,Ghost,Base,sedan,Automatic,sca664s55bux50201,15450,Financial Services Remarketing (Bmw Int),146000,150000,2015-06-04,California,4
33156,2005,Saab,9-2X,Linear,wagon,Automatic,jf4gg61655h056338,38275,Adk Auto Brokers Inc,2900,4000,2015-06-18,New York,10
12919,2008,Saturn,Outlook,XR,suv,Automatic,5gzev23758j168989,115033,Vegas Motorcars Inc,7500,8750,2015-06-19,Nevada,7
36308,2013,Scion,FR-S,Base,coupe,Manual,jf1znaa11d1724601,17484,D&A Fine Cars,18450,16800,2015-06-19,Florida,2
47583,2013,Subaru,XV Crosstrek,Premium,suv,Automatic,jf2gpacc7dh852375,27739,Td Auto Finance,18750,17800,2015-07-09,Texas,2
45640,2007,Suzuki,XL7,Luxury,suv,Automatic,2s3da517176111246,94880,Carworks Inc,4000,5500,2015-07-07,Georgia,8
21076,2013,Tesla,Model S,Base,Sedan,Automatic,5yjsa1cgxdfp19512,25797,Ferrari Of Orange County,59200,55500,2015-05-21,California,2
30029,2012,Toyota,4Runner,SR5,SUV,Automatic,jtebu5jr5c5094399,62296,Mike Albert Fleet Solutions,26500,25100,2015-07-09,Texas,3
9010,2014,Volkswagen,Jetta,SE PZEV,sedan,Automatic,3vwd17aj8em395058,34325,Enterprise Vehicle Exchange / Tra / Rental / T...,11400,7600,2015-07-09,Georgia,1
10651,2007,Volvo,XC90,3.2,suv,Automatic,yv4cy982971355864,95769,Unique Autos,5950,8500,2015-07-09,Nevada,8
15531,2012,smart,fortwo,passion coupe,hatchback,Automatic,wmeej3ba7ck571862,13702,Mercedes-Benz Financial Services,6175,6000,2015-06-18,California,3

### Return vehicles sold in the last 90 days of the entire dataset timeline.

In [14]:
car_sales_df['Sale Date'] = pd.to_datetime(car_sales_df['Sale Date'])
car_sales_df[(car_sales_df['Sale Date'] -max(car_sales_df['Sale Date'])).dt.days <= 90]

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
0,2004,Ford,Explorer,Limited,SUV,Automatic,1fmzu65k54ua59709,171116,Barnett Finance Company,2500,1700,2015-02-17,Georgia,11
1,2013,Chevrolet,Impala,LS Fleet,sedan,Automatic,2g1wf5e3xd1160771,57634,The Hertz Corporation,8925,8900,2015-06-16,California,2
2,2014,Dodge,Grand Caravan,SXT,Minivan,Automatic,2c4rdgcg2er173190,37928,Avis Corporation,16200,16200,2015-02-12,South Carolina,1
3,2007,Ford,F-150,XLT,supercab,Automatic,1ftpx14557fa02257,108246,Tdaf Remarketing,10300,11000,2015-06-16,Florida,8
4,2011,Hyundai,Elantra,GLS PZEV,Sedan,Automatic,5npdh4aexbh018071,69185,Wholesale Inc # 2,9575,10300,2015-01-21,Tennessee,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2013,Nissan,Altima,2.5,Sedan,Automatic,1n4al3ap5dn468314,32702,Nissan-Infiniti Lt,13800,13000,2015-02-26,Illinois,2
49996,2005,Mercedes-Benz,E-Class,E320,Sedan,Automatic,wdbuf65j95a624447,123165,Westlake Financial Services,6075,4100,2015-01-08,Florida,10
49997,2013,Dodge,Dart,SXT,Sedan,Automatic,1c3cdfba9dd143722,47130,Wells Fargo Dealer Services,11400,11000,2015-03-04,Texas,2
49998,2008,Toyota,RAV4,Limited,SUV,Automatic,jtmzd31vx85115663,102712,Infinity Auto Sales Llc,9525,8600,2015-03-05,Virginia,7
49999,2013,Chevrolet,Camaro,SS,Convertible,Automatic,2g1fk3dj8d9138852,53105,Tdaf Remarketing,21400,23400,2015-02-17,Florida,2

### List transactions where Selling Price exceeds the 90th percentile of all selling prices.

In [15]:
car_sales_df[car_sales_df["Selling Price"] > car_sales_df["Selling Price"].quantile(0.9)]

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
17,2014,Buick,Enclave,Premium Group,SUV,Automatic,5gakvckd9ej225953,25352,Gm Remarketing,35200,33700,2015-02-19,Illinois,1
32,2014,Ford,Explorer,Limited,SUV,Automatic,1fm5k8f8xegb11760,36374,Ars/Avis Budget Group,25600,25400,2015-05-27,Minnesota,1
40,2014,GMC,Terrain,SLT-2,SUV,Automatic,2gkflye35e6271285,15841,Gm Remarketing,28100,25900,2015-03-05,Michigan,1
48,2011,Ford,F-250 Super Duty,Lariat,Crew Cab,Automatic,1ft7w2bt5bec62327,41563,Woodhouse Ford Inc,39500,39500,2015-02-05,Texas,4
57,2013,Audi,allroad,Premium Plus quattro,Wagon,Automatic,wa1ufafl8da062327,56262,Fratelli Investment Group,27600,27000,2015-02-12,California,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49956,2013,Lexus,RX 350,Base,SUV,Automatic,2t2bk1ba2dc176716,20345,Lexus Financial Services,34700,33500,2015-02-03,Ohio,2
49965,2012,Fisker,Karma,Eco-Sport,Sedan,Automatic,yh4k14aa4ca000463,18593,Innovative Auto Llc,48200,46500,2015-02-12,Georgia,3
49979,2015,Chevrolet,Suburban,LTZ,SUV,Automatic,1gnsckkc6fr206194,16293,Enterprise Veh Exchange/Rental,52200,51500,2015-02-20,Florida,0
49988,2014,BMW,3 Series,328d xDrive,sedan,Automatic,wba3d5c55ekx99045,3258,Bmw North America Raa,30400,30000,2015-06-16,Ohio,1
49991,2013,Lexus,GS 350,Base,sedan,Automatic,jthbe1bl2d5014108,26897,High Bid Trading Co Inc,30500,31500,2015-06-18,California,2

### Compute the average Selling Price and average Odometer for each State.

In [16]:
car_sales_df.groupby("State").agg({
    "Selling Price":"mean",
    "Odometer":"mean"
})

                Selling Price       Odometer
State
Arizona          12608.962264   68283.826415
California       14944.455471   66328.488742
Colorado         15263.371601   54533.217523
Florida          14182.684945   62313.057951
Georgia          12799.398687   77195.061914
Hawaii           11950.735294   49179.875000
Illinois         15512.140170   43718.676668
Indiana          10506.220096   72863.760766
Louisiana        10579.406780   86152.485876
Maryland          7696.072797   99439.857280
Massachusetts     6946.200000  107881.896000
Michigan         14964.674327   60412.623112
Minnesota        13981.317757   59451.635514
Mississippi      11360.789474   83298.884211
Missouri         14734.617576   58060.864242
Nebraska         12604.745283   72760.667453
Nevada           15433.719572   60671.365132
New Jersey       13495.951567   60008.398046
New Mexico        3307.894737  128555.052632
New York         12847.747495   65002.553106
North Carolina    8840.382729  100776.402146
Ohio             14145.288238   63749.298931
Oklahoma          6978.571429  132019.142857
Oregon           11439.830508   61733.830508
Pennsylvania     14104.973149   57340.891830
Puerto Rico       9852.519380   55293.015504
South Carolina    9880.058081   88795.835859
Tennessee        16968.813259   49483.616903
Texas            13427.319322   71199.721130
Utah             12450.877193   92157.660819
Virginia          8527.886754   99884.278059
Washington       13849.903766   61981.589958
Wisconsin        14236.230539   63436.636727

### For each Make, calculate the total units sold (count of VIN) and the total revenue (sum of Selling Price).

In [17]:
stat=car_sales_df.groupby(["Make"]).agg({
    "Vehicle Identification Number":"nunique",
    "Selling Price":"sum"
})
stat=stat.rename(columns={"Vehicle Identification Number":"Count" , "Selling Price":"Revenue"})
stat

/tmp/ipykernel_47322/3515030555.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

               Count    Revenue
Make
Acura            446    5890075
Aston Martin       6     306100
Audi             476   10099175
BMW             1824   37973575
Bentley            3     188500
Buick            494    4961954
Cadillac         661    9449571
Chevrolet       5773   67809188
Chrysler        1595   16845669
Dodge           2896   31904833
FIAT              87     860725
Fisker             1      46500
Ford            8518  125259319
GMC              934   15859590
Geo                2        850
HUMMER            93    1357050
Honda           2713   29614325
Hyundai         1936   21057828
Infiniti        1466   29826383
Isuzu             13      18600
Jaguar           131    2795800
Jeep            1389   20441200
Kia             1696   19981930
Lamborghini        1     110000
Land Rover       137    4736800
Lexus           1083   21921000
Lincoln          525    9350010
MINI             314    3859425
Maserati          13     548750
Mazda            728    7475879
Mercedes-Benz   1427   31515681
Mercury          133     561150
Mitsubishi       387    3063750
Nissan          4687   55813546
Oldsmobile        44      37675
Plymouth           3      21000
Pontiac          454    1653800
Porsche          111    4524550
Ram              405    9937550
Rolls-Royce        1     150000
Saab              38     102450
Saturn           268     936675
Scion            165    1667700
Subaru           436    6724450
Suzuki            97     380825
Tesla              3     195750
Toyota          3852   47736800
Volkswagen      1165   11138474
Volvo            333    3561675
smart             37     228200

### Compute Delta = Selling Price – Market Price and find the median Delta for each Body style.

In [18]:
new_df=car_sales_df
new_df["Delta"]=car_sales_df["Selling Price"]-car_sales_df["Market Price"]
new_df.groupby("Make")["Delta"].median()

/tmp/ipykernel_47322/2521825665.py:3: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Make
Acura              50.0
Aston Martin    -1100.0
Audi              -50.0
BMW               -75.0
Bentley          4400.0
Buick            -125.0
Cadillac          -25.0
Chevrolet           0.0
Chrysler         -100.0
Dodge             -50.0
FIAT               50.0
Fisker          -1700.0
Ford              -75.0
GMC                12.5
Geo              -250.0
HUMMER            175.0
Honda              25.0
Hyundai             0.0
Infiniti          -50.0
Isuzu              75.0
Jaguar           -125.0
Jeep              -50.0
Kia                 0.0
Lamborghini     -1000.0
Land Rover       -300.0
Lexus               0.0
Lincoln           -50.0
MINI              -50.0
Maserati           50.0
Mazda              50.0
Mercedes-Benz    -200.0
Mercury          -150.0
Mitsubishi          0.0
Nissan              0.0
Oldsmobile       -125.0
Plymouth         -250.0
Pontiac          -225.0
Porsche            50.0
Ram               -50.0
Rolls-Royce      4000.0
Saab             -137.5
Saturn           -112.5
Scion               0.0
Subaru            -50.0
Suzuki            -25.0
Tesla           -3700.0
Toyota            -50.0
Volkswagen        -25.0
Volvo            -100.0
smart             -75.0
Name: Delta, dtype: float64

### Produce a quarter‑wise (3‑month) count of sales transactions across the whole dataset.

In [19]:
new_df=car_sales_df
new_df=new_df.set_index("Sale Date")
resampled_df=new_df.resample("3ME")["Selling Price"].size()
resampled_df=pd.DataFrame(resampled_df)
resampled_df=resampled_df.rename(columns={0:"Count"})
resampled_df.index=resampled_df.index.to_period("Q")
resampled_df.index=[f"{p.year}-Q{p.quarter}" for p in resampled_df.index]
resampled_df

         Selling Price
2014-Q1             19
2014-Q2              0
2014-Q3              0
2014-Q4              0
2015-Q1          16793
2015-Q2          19254
2015-Q3          13934

### For each State, calculate annual revenue (sum of Selling Price) and the year‑over‑year growth %.

In [20]:
new_df=car_sales_df
new_df["Sale Year"]=car_sales_df["Sale Date"].dt.year
new_df=car_sales_df.groupby(["State","Sale Year"])[["Selling Price"]].sum()
new_df["year_over_growth(%)"]=new_df["Selling Price"].pct_change()
new_df

                      Selling Price  year_over_growth(%)
State      Sale Year
Arizona    2014             1125550                  NaN
           2015             8898575             6.905979
California 2014            12979350             0.458587
           2015            91228338             6.028729
Colorado   2014              732700            -0.991969
...                             ...                  ...
Virginia   2015             7611080             8.247971
Washington 2014              623150            -0.918126
           2015             9307231            13.935780
Wisconsin  2014              758275            -0.918528
           2015            13506428            16.812044

[64 rows x 2 columns]

### Resample the data to a monthly frequency and compute the mean Selling Price for each month.

In [21]:
new_df=car_sales_df
new_df["Sale Date"]=pd.to_datetime(car_sales_df["Sale Date"])
new_df=new_df.set_index("Sale Date")
display(new_df.index)
new_df=new_df.resample("ME")[["Selling Price"]].mean()
new_df["Selling Price"].fillna(0)

DatetimeIndex(['2015-02-17', '2015-06-16', '2015-02-12', '2015-06-16',
               '2015-01-21', '2015-02-25', '2015-02-10', '2015-01-15',
               '2015-06-03', '2015-05-22',
               ...
               '2015-05-20', '2015-06-18', '2015-02-04', '2015-02-04',
               '2015-06-10', '2015-02-26', '2015-01-08', '2015-03-04',
               '2015-03-05', '2015-02-17'],
              dtype='datetime64[ns]', name='Sale Date', length=50000, freq=None)

Sale Date
2014-01-31    12834.210526
2014-02-28        0.000000
2014-03-31        0.000000
2014-04-30        0.000000
2014-05-31        0.000000
2014-06-30        0.000000
2014-07-31        0.000000
2014-08-31        0.000000
2014-09-30        0.000000
2014-10-31        0.000000
2014-11-30        0.000000
2014-12-31    12600.545408
2015-01-31    13147.514126
2015-02-28    13635.189065
2015-03-31    13664.699366
2015-04-30    10419.893617
2015-05-31    13855.259815
2015-06-30    14519.394849
2015-07-31    16231.390909
Freq: ME, Name: Selling Price, dtype: float64

### Resample to a weekly frequency (weeks ending on Sunday) and count the number of sales per week.

In [22]:
new_df=car_sales_df
new_df["Sale Date"]=pd.to_datetime(car_sales_df["Sale Date"])
new_df=new_df.set_index("Sale Date")
new_df=new_df.resample("W")[["Selling Price"]].size()
new_df=pd.DataFrame(new_df)
new_df=new_df.rename(columns={0:"Count"})
new_df

            Count
Sale Date
2014-01-05      7
2014-01-12     12
2014-01-19      0
2014-01-26      0
2014-02-02      0
...           ...
2015-06-14   2070
2015-06-21   3279
2015-06-28     27
2015-07-05     58
2015-07-12     70

[80 rows x 1 columns]

### Calculate a centered 6‑month rolling average of Odometer based on Sale Date.

In [23]:
new_df=car_sales_df
new_df["Sale Date"]=pd.to_datetime(car_sales_df["Sale Date"])
new_df=new_df.set_index("Sale Date")
monthly_odo=new_df.resample("ME")["Odometer"].mean()
roll_df=monthly_odo.rolling(window=6,center=True).mean().to_frame()
roll_df=roll_df["Odometer"].fillna(0)
roll_df

Sale Date
2014-01-31        0.000000
2014-02-28        0.000000
2014-03-31        0.000000
2014-04-30        0.000000
2014-05-31        0.000000
2014-06-30        0.000000
2014-07-31        0.000000
2014-08-31        0.000000
2014-09-30        0.000000
2014-10-31        0.000000
2014-11-30        0.000000
2014-12-31        0.000000
2015-01-31        0.000000
2015-02-28        0.000000
2015-03-31    71051.742472
2015-04-30    69179.206134
2015-05-31    67072.588336
2015-06-30        0.000000
2015-07-31        0.000000
Freq: ME, Name: Odometer, dtype: float64

### For each month, extract the Selling Price of the first sale (minimum Sale Date within that month).

In [24]:
new_df=car_sales_df
new_df["Sale Date"]=pd.to_datetime(car_sales_df["Sale Date"])
new_df=new_df.set_index("Sale Date")
print(type(new_df.index))
new_df=new_df.resample("ME").first()[["Selling Price"]]
new_df["Selling Price"].fillna(0)
new_df.index=new_df.index.to_period("M")
new_df

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

           Selling Price
Sale Date
2014-01          10500.0
2014-02              NaN
2014-03              NaN
2014-04              NaN
2014-05              NaN
2014-06              NaN
2014-07              NaN
2014-08              NaN
2014-09              NaN
2014-10              NaN
2014-11              NaN
2014-12          20300.0
2015-01          11600.0
2015-02          17800.0
2015-03          11400.0
2015-04           4200.0
2015-05           2600.0
2015-06           7400.0
2015-07          13200.0

### Generate a cumulative revenue series ordered by Sale Date.

In [25]:
new_df=car_sales_df
new_df["Sale Date"]=pd.to_datetime(car_sales_df["Sale Date"])
new_df=new_df.set_index("Sale Date")
before_cumm_sum=new_df.resample("ME")[["Selling Price"]].sum()
cumm_sum=before_cumm_sum.cumsum()
cumm_sum.sort_values("Selling Price")
cumm_sum.rename(columns={"Selling Price":"Cummulative Sum"},inplace=True)
cumm_sum

            Cummulative Sum
Sale Date
2014-01-31           243850
2014-02-28           243850
2014-03-31           243850
2014-04-30           243850
2014-05-31           243850
2014-06-30           243850
2014-07-31           243850
2014-08-31           243850
2014-09-30           243850
2014-10-31           243850
2014-11-30           243850
2014-12-31         49499382
2015-01-31        218891954
2015-02-28        421401782
2015-03-31        479627066
2015-04-30        481096271
2015-05-31        545675637
2015-06-30        678716852
2015-07-31        680502305