In [1]:
import pandas as pd
import plotly.express as px

In [7]:
ecu_df=pd.read_csv("F:\KPIT\Pandas_All\Datasets\ecu_sensor_data.csv")
ecu_df["unit"]=pd.Categorical(ecu_df["unit"])

In [8]:
ecu_df.sample(5)

                 timestamp vehicle_id        sensor_type    value     unit
18353  2025-10-01 13:05:53     VEH002  throttle_position    45.63        %
4640   2025-10-01 09:17:20     VEH004         engine_rpm  2906.99      RPM
6005   2025-10-01 09:40:05     VEH004      oxygen_sensor     0.87    Volts
18421  2025-10-01 13:07:01     VEH004  throttle_position    27.86        %
10489  2025-10-01 10:54:49     VEH003       coolant_temp    77.26  Celsius

In [9]:
ecu_df.columns

Index(['timestamp', 'vehicle_id', 'sensor_type', 'value', 'unit'], dtype='object')

In [10]:
ecu_df.index

RangeIndex(start=0, stop=20000, step=1)

In [18]:
# Display the total number of unique vehicles and sensor types in the dataset.
unique_vehicle=ecu_df["vehicle_id"].nunique()
unique_sensor_type=ecu_df["sensor_type"].nunique()
display(unique_vehicle)
display(unique_sensor_type)

4

4

In [ ]:
#Find the top 3 most frequently recorded sensor types.
freq=ecu_df.groupby("sensor_type").size()
freq_df=pd.DataFrame(freq)
freq_df=freq_df.rename(columns={0:"Count"})
freq_df.sort_values("Count",ascending=False).head(3)

                   Count
sensor_type
coolant_temp        5019
engine_rpm          4930
oxygen_sensor       5129
throttle_position   4922

               Count
sensor_type
oxygen_sensor   5129
coolant_temp    5019
engine_rpm      4930

In [32]:
# Calculate the mean, median, and standard deviation of sensor value for each sensor_type.
ecu_df.groupby("sensor_type").describe()

                    value                                                      \
                    count         mean         std    min        25%      50%
sensor_type
coolant_temp       5019.0    84.852234    9.916927   60.0    78.0800    84.74
engine_rpm         4930.0  2510.969132  498.163123  800.0  2171.6125  2507.70
oxygen_sensor      5129.0     0.703295    0.201137    0.1     0.5700     0.71
throttle_position  4922.0    30.072511   14.521925    0.0    19.8500    30.05


                        75%      max
sensor_type
coolant_temp         91.715   110.00
engine_rpm         2853.385  4056.46
oxygen_sensor         0.840     1.20
throttle_position    39.820    81.43

In [36]:
# Identify which vehicle_id has the highest overall average sensor value.
mx=ecu_df.groupby("vehicle_id")["value"].max()
mx=pd.DataFrame(mx)
mx.sort_values("value",ascending=False).head(1)

              value
vehicle_id
VEH003      4056.46

In [46]:
# Plot a boxplot (using Plotly Express) showing the distribution of value across all sensor_types.
res=ecu_df["sensor_type"].value_counts()
res=pd.DataFrame(res)
display(res)
px.box(data_frame=ecu_df,x="sensor_type",y="value",points="all")

                   count
sensor_type
oxygen_sensor       5129
coolant_temp        5019
engine_rpm          4930
throttle_position   4922

In [48]:
# Filter all records where the sensor_type is "coolant_temp" and the value exceeds 95°C.
display(ecu_df.sample(5))
ecu_df[(ecu_df["sensor_type"]=="coolant_temp") & (ecu_df["value"]>95) & (ecu_df["unit"] == "Celsius")]

                 timestamp vehicle_id        sensor_type    value     unit
1908   2025-10-01 08:31:48     VEH003       coolant_temp    73.06  Celsius
6559   2025-10-01 09:49:19     VEH001         engine_rpm  3201.00      RPM
14545  2025-10-01 12:02:25     VEH002      oxygen_sensor     0.39    Volts
1909   2025-10-01 08:31:49     VEH002  throttle_position    32.14        %
10650  2025-10-01 10:57:30     VEH002         engine_rpm  2390.29      RPM

                 timestamp vehicle_id   sensor_type   value     unit
6      2025-10-01 08:00:06     VEH002  coolant_temp  100.79  Celsius
47     2025-10-01 08:00:47     VEH001  coolant_temp   95.57  Celsius
67     2025-10-01 08:01:07     VEH001  coolant_temp   95.04  Celsius
122    2025-10-01 08:02:02     VEH003  coolant_temp   99.03  Celsius
156    2025-10-01 08:02:36     VEH002  coolant_temp  103.66  Celsius
...                    ...        ...           ...     ...      ...
19882  2025-10-01 13:31:22     VEH001  coolant_temp   98.54  Celsius
19898  2025-10-01 13:31:38     VEH003  coolant_temp   95.43  Celsius
19937  2025-10-01 13:32:17     VEH002  coolant_temp  108.40  Celsius
19958  2025-10-01 13:32:38     VEH001  coolant_temp  102.47  Celsius
19988  2025-10-01 13:33:08     VEH003  coolant_temp  105.37  Celsius

[786 rows x 5 columns]

In [51]:
# Retrieve all rows where vehicle_id is "VEH002" and timestamp is between "2025-10-01 09:00:00" and "2025-10-01 09:15:00".
ecu_df["timestamp"] = pd.to_datetime(ecu_df["timestamp"])
ross=ecu_df[(ecu_df["vehicle_id"]=="VEH002") & (ecu_df["timestamp"] > "2025-10-01 09:00:00") & (ecu_df["timestamp"] < "2025-10-01 09:15:00")]
ross

               timestamp vehicle_id        sensor_type    value     unit
3602 2025-10-01 09:00:02     VEH002       coolant_temp   105.50  Celsius
3609 2025-10-01 09:00:09     VEH002       coolant_temp    80.85  Celsius
3610 2025-10-01 09:00:10     VEH002         engine_rpm  2517.01      RPM
3611 2025-10-01 09:00:11     VEH002         engine_rpm  2555.69      RPM
3612 2025-10-01 09:00:12     VEH002  throttle_position    27.31        %
...                  ...        ...                ...      ...      ...
4487 2025-10-01 09:14:47     VEH002         engine_rpm  2211.04      RPM
4490 2025-10-01 09:14:50     VEH002       coolant_temp    88.95  Celsius
4493 2025-10-01 09:14:53     VEH002       coolant_temp    80.41  Celsius
4494 2025-10-01 09:14:54     VEH002  throttle_position    42.85        %
4499 2025-10-01 09:14:59     VEH002       coolant_temp    73.06  Celsius

[221 rows x 5 columns]

In [52]:
# Find all instances where sensor_type is "engine_rpm" and value is greater than 4000 RPM.
ecu_df[(ecu_df["sensor_type"] == "engine_rpm") & (ecu_df["value"] > 4000) & (ecu_df["unit"] == "RPM")]

                timestamp vehicle_id sensor_type    value unit
478   2025-10-01 08:07:58     VEH004  engine_rpm  4039.44  RPM
4997  2025-10-01 09:23:17     VEH003  engine_rpm  4056.46  RPM
17436 2025-10-01 12:50:36     VEH004  engine_rpm  4048.35  RPM

In [53]:
# Group the data by vehicle_id and sensor_type, and find the average value for each combination.
ecu_df.groupby(["vehicle_id","sensor_type"])["value"].mean()

vehicle_id  sensor_type
VEH001      coolant_temp           84.602872
            engine_rpm           2484.134063
            oxygen_sensor           0.702710
            throttle_position      29.711090
VEH002      coolant_temp           85.078692
            engine_rpm           2535.319673
            oxygen_sensor           0.710822
            throttle_position      29.982293
VEH003      coolant_temp           84.818223
            engine_rpm           2512.778469
            oxygen_sensor           0.705842
            throttle_position      30.300691
VEH004      coolant_temp           84.909953
            engine_rpm           2511.859151
            oxygen_sensor           0.694267
            throttle_position      30.312589
Name: value, dtype: float64

In [59]:
# Create a pivot table with vehicle_id as rows, sensor_type as columns, and mean value as the values.
pd.pivot_table(data=ecu_df,index="vehicle_id",values="value",aggfunc="mean")

                 value
vehicle_id
VEH001      636.931074
VEH002      660.308490
VEH003      637.979090
VEH004      656.155036

In [64]:
# Plot a bar graph (using Plotly Express) showing the average sensor value per sensor_type.
avg=ecu_df.groupby("sensor_type")["value"].mean()
avg=pd.DataFrame(avg)
px.bar(data_frame=avg,color=avg.index)

###
🕒 Time-based Analysis & Resampling

Convert timestamp to datetime and resample the data by minute, computing the mean value for each sensor type.

Plot a line graph showing the trend of average engine_rpm over time (using Plotly Express).

For each vehicle, compute the maximum coolant temperature per hour.

🧩 Melting & Reshaping

Pivot the dataset so that each sensor_type becomes a column, then melt it back to long format — showing how data can be reshaped for analysis.
###

In [ ]:
#