In [61]:
import pandas as pd
import plotly.express as px

In [62]:
dtc_df=df=pd.read_csv(r"F:\KPIT\Pandas_All\Datasets\dtc_codes.csv",index_col="timestamp")
sensor_df=pd.read_csv(r"F:\KPIT\Pandas_All\Datasets\ecu_sensor_data.csv",index_col="timestamp")
display(dtc_df.sample(5))
display(sensor_df.sample(5))

,vehicle_id,dtc_code,description,severity
timestamp,,,,
2025-10-01 12:14:47,VEH002,P0420,Catalyst System Efficiency Below Threshold,Low
2025-10-01 08:04:21,VEH003,P0301,Cylinder 1 Misfire Detected,High
2025-10-01 09:21:33,VEH004,P0171,System Too Lean,Medium
2025-10-01 09:52:20,VEH002,P0171,System Too Lean,Medium
2025-10-01 13:32:56,VEH003,P0301,Cylinder 1 Misfire Detected,High

                    vehicle_id        sensor_type    value     unit
timestamp
2025-10-01 11:01:02     VEH004      oxygen_sensor     0.70    Volts
2025-10-01 08:12:15     VEH001      oxygen_sensor     0.79    Volts
2025-10-01 08:59:27     VEH001         engine_rpm  3037.16      RPM
2025-10-01 08:43:42     VEH002  throttle_position    31.26        %
2025-10-01 12:32:35     VEH001       coolant_temp    84.46  Celsius

In [63]:
display(dtc_df.index)
display(sensor_df.index)

Index(['2025-10-01 08:00:00', '2025-10-01 08:00:02', '2025-10-01 08:00:08',
       '2025-10-01 08:00:14', '2025-10-01 08:00:16', '2025-10-01 08:00:38',
       '2025-10-01 08:00:47', '2025-10-01 08:00:55', '2025-10-01 08:01:00',
       '2025-10-01 08:01:02',
       ...
       '2025-10-01 13:32:17', '2025-10-01 13:32:18', '2025-10-01 13:32:29',
       '2025-10-01 13:32:33', '2025-10-01 13:32:50', '2025-10-01 13:32:54',
       '2025-10-01 13:32:56', '2025-10-01 13:32:59', '2025-10-01 13:33:06',
       '2025-10-01 13:33:18'],
      dtype='object', name='timestamp', length=2025)

Index(['2025-10-01 08:00:00', '2025-10-01 08:00:01', '2025-10-01 08:00:02',
       '2025-10-01 08:00:03', '2025-10-01 08:00:04', '2025-10-01 08:00:05',
       '2025-10-01 08:00:06', '2025-10-01 08:00:07', '2025-10-01 08:00:08',
       '2025-10-01 08:00:09',
       ...
       '2025-10-01 13:33:10', '2025-10-01 13:33:11', '2025-10-01 13:33:12',
       '2025-10-01 13:33:13', '2025-10-01 13:33:14', '2025-10-01 13:33:15',
       '2025-10-01 13:33:16', '2025-10-01 13:33:17', '2025-10-01 13:33:18',
       '2025-10-01 13:33:19'],
      dtype='object', name='timestamp', length=20000)

In [64]:
sensor_types=sensor_df["sensor_type"].value_counts(normalize=True)*100
sensor_types

sensor_type
oxygen_sensor        25.645
coolant_temp         25.095
engine_rpm           24.650
throttle_position    24.610
Name: proportion, dtype: float64

In [65]:
px.bar(sensor_types,color=sensor_types.index)

In [66]:
agg_data=sensor_df.groupby("sensor_type")[["value"]].agg(["min","max","mean"])
display(agg_data)
agg_data.columns=["_".join(col) for col in agg_data.columns]
agg_data.columns
display(agg_data.index)

                   value
                     min      max         mean
sensor_type
coolant_temp        60.0   110.00    84.852234
engine_rpm         800.0  4056.46  2510.969132
oxygen_sensor        0.1     1.20     0.703295
throttle_position    0.0    81.43    30.072511

Index(['coolant_temp', 'engine_rpm', 'oxygen_sensor', 'throttle_position'], dtype='object', name='sensor_type')

In [67]:

px.bar(data_frame=agg_data,barmode="group",facet_col=agg_data.index)

In [68]:
for grp in agg_data.index:
    display(px.bar(data_frame=agg_data.loc[grp],color=agg_data.columns))

In [69]:
sensor_df.index=pd.to_datetime(sensor_df.index)
min_freq=sensor_df.resample("1min")[["value"]].mean()
# min_freq=min_freq.unstack(0)
min_freq

                          value
timestamp
2025-10-01 08:00:00  692.547833
2025-10-01 08:01:00  902.920000
2025-10-01 08:02:00  662.052667
2025-10-01 08:03:00  495.253500
2025-10-01 08:04:00  593.545167
...                         ...
2025-10-01 13:29:00  711.030167
2025-10-01 13:30:00  819.415833
2025-10-01 13:31:00  502.711333
2025-10-01 13:32:00  475.755833
2025-10-01 13:33:00  963.390000

[334 rows x 1 columns]

In [ ]:
sensor_df_agg=sensor_df.groupby("sensor_type",observed=True).resample("1min")[["value"]].mean()
sensor_df_agg=sensor_df_agg.unstack(0)
sensor_df_agg.columns=[idx[1]+"_"+idx[0] for idx in sensor_df_agg.columns]
sensor_df_agg

,coolant_temp_value,engine_rpm_value,oxygen_sensor_value,throttle_position_value
timestamp,,,,
2025-10-01 08:00:00,84.657778,2330.244118,0.743333,25.511875
2025-10-01 08:01:00,81.377059,2625.338500,0.710000,30.564444
2025-10-01 08:02:00,83.586111,2683.799286,0.764286,30.479524
2025-10-01 08:03:00,84.975625,2538.041818,0.690000,32.564615
2025-10-01 08:04:00,83.243750,2413.145714,0.765000,30.378750
...,...,...,...,...
2025-10-01 13:29:00,84.671333,2732.630000,0.705294,30.023077
2025-10-01 13:30:00,80.752143,2642.737778,0.816923,30.301333
2025-10-01 13:31:00,87.288333,2596.415455,0.684667,24.744545
2025-10-01 13:32:00,85.116000,2202.340000,0.758462,27.006000
2025-10-01 13:33:00,84.120000,2699.770000,0.820000,28.032500

In [77]:
for col in sensor_df_agg:
    display(px.line(sensor_df_agg,x=sensor_df_agg.index,y=sensor_df_agg[col],markers=True))

In [79]:
res=dtc_df.groupby(["dtc_code","severity"])["severity"].size().unstack()
res

severity   High    Low  Medium
dtc_code
P0128       NaN  401.0     NaN
P0135       NaN    NaN   430.0
P0171       NaN    NaN   391.0
P0301     374.0    NaN     NaN
P0420       NaN  429.0     NaN

In [82]:
merged_dff=sensor_df.merge(dtc_df,left_on="vehicle_id",right_on="vehicle_id",how="outer")

In [84]:
merged_df=merged_dff.drop_duplicates()
merged_df

,vehicle_id,sensor_type,value,unit,dtc_code,description,severity
0,VEH001,engine_rpm,2748.36,RPM,P0301,Cylinder 1 Misfire Detected,High
3,VEH001,engine_rpm,2748.36,RPM,P0128,Coolant Thermostat Malfunction,Low
5,VEH001,engine_rpm,2748.36,RPM,P0420,Catalyst System Efficiency Below Threshold,Low
6,VEH001,engine_rpm,2748.36,RPM,P0171,System Too Lean,Medium
12,VEH001,engine_rpm,2748.36,RPM,P0135,O2 Sensor Heater Circuit,Medium
...,...,...,...,...,...,...,...
10126248,VEH004,engine_rpm,2693.91,RPM,P0135,O2 Sensor Heater Circuit,Medium
10126250,VEH004,engine_rpm,2693.91,RPM,P0301,Cylinder 1 Misfire Detected,High
10126251,VEH004,engine_rpm,2693.91,RPM,P0171,System Too Lean,Medium
10126259,VEH004,engine_rpm,2693.91,RPM,P0128,Coolant Thermostat Malfunction,Low
10126264,VEH004,engine_rpm,2693.91,RPM,P0420,Catalyst System Efficiency Below Threshold,Low

In [85]:
grouped_df=merged_df.groupby("vehicle_id")
grouped_df

In [86]:
grouped_df.groups

{'VEH001': [0, 3, 5, 6, 12, 510, 513, 515, 516, 522, 1020, 1023, 1025, 1026, 1032, 1530, 1533, 1535, 1536, 1542, 2040, 2043, 2045, 2046, 2052, 2550, 2553, 2555, 2556, 2562, 3060, 3063, 3065, 3066, 3072, 3570, 3573, 3575, 3576, 3582, 4080, 4083, 4085, 4086, 4092, 4590, 4593, 4595, 4596, 4602, 5100, 5103, 5105, 5106, 5112, 5610, 5613, 5615, 5616, 5622, 6120, 6123, 6125, 6126, 6132, 6630, 6633, 6635, 6636, 6642, 7140, 7143, 7145, 7146, 7152, 7650, 7653, 7655, 7656, 7662, 8160, 8163, 8165, 8166, 8172, 8670, 8673, 8675, 8676, 8682, 9180, 9183, 9185, 9186, 9192, 9690, 9693, 9695, 9696, 9702, ...], 'VEH002': [2569890, 2569891, 2569894, 2569895, 2569899, 2570384, 2570385, 2570388, 2570389, 2570393, 2570878, 2570879, 2570882, 2570883, 2570887, 2571372, 2571373, 2571376, 2571377, 2571381, 2571866, 2571867, 2571870, 2571871, 2571875, 2572360, 2572361, 2572364, 2572365, 2572369, 2572854, 2572855, 2572858, 2572859, 2572863, 2573348, 2573349, 2573352, 2573353, 2573357, 2573842, 2573843, 2573846, 2573847, 2573851, 2574336, 2574337, 2574340, 2574341, 2574345, 2574830, 2574831, 2574834, 2574835, 2574839, 2575324, 2575325, 2575328, 2575329, 2575333, 2575818, 2575819, 2575822, 2575823, 2575827, 2576312, 2576313, 2576316, 2576317, 2576321, 2576806, 2576807, 2576810, 2576811, 2576815, 2577300, 2577301, 2577304, 2577305, 2577309, 2577794, 2577795, 2577798, 2577799, 2577803, 2578288, 2578289, 2578292, 2578293, 2578297, 2579276, 2579277, 2579280, 2579281, 2579285, 2579770, 2579771, 2579774, 2579775, 2579779, ...], 'VEH003': [4996912, 4996913, 4996914, 4996915, 4996919, 4997420, 4997421, 4997422, 4997423, 4997427, 4997928, 4997929, 4997930, 4997931, 4997935, 4998436, 4998437, 4998438, 4998439, 4998443, 4998944, 4998945, 4998946, 4998947, 4998951, 4999452, 4999453, 4999454, 4999455, 4999459, 4999960, 4999961, 4999962, 4999963, 4999967, 5000468, 5000469, 5000470, 5000471, 5000475, 5000976, 5000977, 5000978, 5000979, 5000983, 5001484, 5001485, 5001486, 5001487, 5001491, 5001992, 5001993, 5001994, 5001995, 5001999, 5002500, 5002501, 5002502, 5002503, 5002507, 5003008, 5003009, 5003010, 5003011, 5003015, 5003516, 5003517, 5003518, 5003519, 5003523, 5004024, 5004025, 5004026, 5004027, 5004031, 5004532, 5004533, 5004534, 5004535, 5004539, 5005040, 5005041, 5005042, 5005043, 5005047, 5005548, 5005549, 5005550, 5005551, 5005555, 5006056, 5006057, 5006058, 5006059, 5006063, 5006564, 5006565, 5006566, 5006567, 5006571, ...], 'VEH004': [7514052, 7514054, 7514055, 7514063, 7514068, 7514565, 7514567, 7514568, 7514576, 7514581, 7515078, 7515080, 7515081, 7515089, 7515094, 7515591, 7515593, 7515594, 7515602, 7515607, 7516104, 7516106, 7516107, 7516115, 7516120, 7516617, 7516619, 7516620, 7516628, 7516633, 7517130, 7517132, 7517133, 7517141, 7517146, 7517643, 7517645, 7517646, 7517654, 7517659, 7518156, 7518158, 7518159, 7518167, 7518172, 7518669, 7518671, 7518672, 7518680, 7518685, 7519182, 7519184, 7519185, 7519193, 7519198, 7519695, 7519697, 7519698, 7519706, 7519711, 7520208, 7520210, 7520211, 7520219, 7520224, 7520721, 7520723, 7520724, 7520732, 7520737, 7521234, 7521236, 7521237, 7521245, 7521250, 7521747, 7521749, 7521750, 7521758, 7521763, 7522260, 7522262, 7522263, 7522271, 7522276, 7522773, 7522775, 7522776, 7522784, 7522789, 7523286, 7523288, 7523289, 7523297, 7523302, 7523799, 7523801, 7523802, 7523810, 7523815, ...]}

In [ ]:
excel_path="resulted_excel.xlsx"
with pd.ExcelWriter(excel_path) as excel_file:
    for grp in grouped_df.groups:
        grouped_df.get_group(grp).to_excel(excel_file,sheet_name=grp)

In [89]:
dataframe=[]
excel_path=r"resulted_excel.xlsx"
for grp in grouped_df.groups:
    dataframe.append(pd.read_excel(excel_path,sheet_name=grp))
    
dataframe

[       Unnamed: 0 vehicle_id   sensor_type    value     unit dtc_code  \
 0               0     VEH001    engine_rpm  2748.36      RPM    P0301
 1               3     VEH001    engine_rpm  2748.36      RPM    P0128
 2               5     VEH001    engine_rpm  2748.36      RPM    P0420
 3               6     VEH001    engine_rpm  2748.36      RPM    P0171
 4              12     VEH001    engine_rpm  2748.36      RPM    P0135
 ...           ...        ...           ...      ...      ...      ...
 17750     2569380     VEH001  coolant_temp    68.80  Celsius    P0301
 17751     2569383     VEH001  coolant_temp    68.80  Celsius    P0128
 17752     2569385     VEH001  coolant_temp    68.80  Celsius    P0420
 17753     2569386     VEH001  coolant_temp    68.80  Celsius    P0171
 17754     2569392     VEH001  coolant_temp    68.80  Celsius    P0135

                                       description severity
 0                     Cylinder 1 Misfire Detected     High
 1                  Coolant Thermostat Malfunction      Low
 2      Catalyst System Efficiency Below Threshold      Low
 3                                 System Too Lean   Medium
 4                        O2 Sensor Heater Circuit   Medium
 ...                                           ...      ...
 17750                 Cylinder 1 Misfire Detected     High
 17751              Coolant Thermostat Malfunction      Low
 17752  Catalyst System Efficiency Below Threshold      Low
 17753                             System Too Lean   Medium
 17754                    O2 Sensor Heater Circuit   Medium

 [17755 rows x 8 columns],
        Unnamed: 0 vehicle_id        sensor_type  value     unit dtc_code  \
 0         2569890     VEH002       coolant_temp  91.48  Celsius    P0171
 1         2569891     VEH002       coolant_temp  91.48  Celsius    P0420
 2         2569894     VEH002       coolant_temp  91.48  Celsius    P0301
 3         2569895     VEH002       coolant_temp  91.48  Celsius    P0128
 4         2569899     VEH002       coolant_temp  91.48  Celsius    P0135
 ...           ...        ...                ...    ...      ...      ...
 17090     4996418     VEH002  throttle_position  35.68        %    P0171
 17091     4996419     VEH002  throttle_position  35.68        %    P0420
 17092     4996422     VEH002  throttle_position  35.68        %    P0301
 17093     4996423     VEH002  throttle_position  35.68        %    P0128
 17094     4996427     VEH002  throttle_position  35.68        %    P0135

                                       description severity
 0                                 System Too Lean   Medium
 1      Catalyst System Efficiency Below Threshold      Low
 2                     Cylinder 1 Misfire Detected     High
 3                  Coolant Thermostat Malfunction      Low
 4                        O2 Sensor Heater Circuit   Medium
 ...                                           ...      ...
 17090                             System Too Lean   Medium
 17091  Catalyst System Efficiency Below Threshold      Low
 17092                 Cylinder 1 Misfire Detected     High
 17093              Coolant Thermostat Malfunction      Low
 17094                    O2 Sensor Heater Circuit   Medium

 [17095 rows x 8 columns],
        Unnamed: 0 vehicle_id   sensor_type    value     unit dtc_code  \
 0         4996912     VEH003  coolant_temp    83.62  Celsius    P0128
 1         4996913     VEH003  coolant_temp    83.62  Celsius    P0171
 2         4996914     VEH003  coolant_temp    83.62  Celsius    P0420
 3         4996915     VEH003  coolant_temp    83.62  Celsius    P0135
 4         4996919     VEH003  coolant_temp    83.62  Celsius    P0301
 ...           ...        ...           ...      ...      ...      ...
 16945     7513544     VEH003    engine_rpm  3188.68      RPM    P0128
 16946     7513545     VEH003    engine_rpm  3188.68      RPM    P0171
 16947     7513546     VEH003    engine_rpm  3188.68      RPM    P0420
 16948     7513547     VEH003    engine_rpm  3188.68      RPM    P0135
 16949     7513551     VEH003    engine_rpm  3188.68      RPM    P0301

                                       description severity
 0                  Coolant Thermostat Malfunction      Low
 1                                 System Too Lean   Medium
 2      Catalyst System Efficiency Below Threshold      Low
 3                        O2 Sensor Heater Circuit   Medium
 4                     Cylinder 1 Misfire Detected     High
 ...                                           ...      ...
 16945              Coolant Thermostat Malfunction      Low
 16946                             System Too Lean   Medium
 16947  Catalyst System Efficiency Below Threshold      Low
 16948                    O2 Sensor Heater Circuit   Medium
 16949                 Cylinder 1 Misfire Detected     High

 [16950 rows x 8 columns],
        Unnamed: 0 vehicle_id sensor_type    value unit dtc_code  \
 0         7514052     VEH004  engine_rpm  2382.92  RPM    P0135
 1         7514054     VEH004  engine_rpm  2382.92  RPM    P0301
 2         7514055     VEH004  engine_rpm  2382.92  RPM    P0171
 3         7514063     VEH004  engine_rpm  2382.92  RPM    P0128
 4         7514068     VEH004  engine_rpm  2382.92  RPM    P0420
 ...           ...        ...         ...      ...  ...      ...
 17515    10126248     VEH004  engine_rpm  2693.91  RPM    P0135
 17516    10126250     VEH004  engine_rpm  2693.91  RPM    P0301
 17517    10126251     VEH004  engine_rpm  2693.91  RPM    P0171
 17518    10126259     VEH004  engine_rpm  2693.91  RPM    P0128
 17519    10126264     VEH004  engine_rpm  2693.91  RPM    P0420

                                       description severity
 0                        O2 Sensor Heater Circuit   Medium
 1                     Cylinder 1 Misfire Detected     High
 2                                 System Too Lean   Medium
 3                  Coolant Thermostat Malfunction      Low
 4      Catalyst System Efficiency Below Threshold      Low
 ...                                           ...      ...
 17515                    O2 Sensor Heater Circuit   Medium
 17516                 Cylinder 1 Misfire Detected     High
 17517                             System Too Lean   Medium
 17518              Coolant Thermostat Malfunction      Low
 17519  Catalyst System Efficiency Below Threshold      Low

 [17520 rows x 8 columns]]